name: Build and Deploy Vuepress Blog To Linux 
on: 
  push: 
    branches: [ master ]
    paths: 
      - '.github/workflows/**'
      - 'docs/**'
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@master 

    - name: set ssh key # 临时设置 ssh key