name: Build and Deploy Vuepress Blog To Linux 
on: 
  push: 
    branches: [ master ]
    paths: 
      - '.github/workflows/**'
      - 'docs/**'
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout   # 获取最新代码
      uses: actions/checkout@master 

    - name: use Node.js 10
      uses: actions/setup-node@v1
      with:
          node-version: 12

    - name: npm install and build
      run: |
        npm install 
        npm run build

    - name: Deploy 
      uses: easingthemes/ssh-deploy@main  
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: '-avz --delete'
          SOURCE: 'docs/.vuepress/dist'
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: '/usr/share/nginx/html/blog'


    